_wandb:
    value:
        cli_version: 0.26.1
        e:
            069cc3y7shz1lpashpt5fjqcs8mruyus:
                args:
                    - train
                    - config/modelo_mar_bueno.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "510301040640"
                        used: "453635731456"
                email: mar.dijort@estudiantat.upc.edu
                executable: C:\Users\dijor\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                git:
                    commit: db0804a7cbdb044335d63b7d58678ecdb33b1dca
                    remote: https://github.com/laurarebollocrespo/ML-WiFi-Sensing-Classification.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-f3f602d3-c2d8-565a-477e-6dc6707a8206
                host: DESKTOP-61IUEAH
                memory:
                    total: "16369225728"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\dijor\Q4\AA1\ML-WiFi-Sensing-Classification\main.py
                python: CPython 3.13.13
                root: C:\Users\dijor\Q4\AA1\ML-WiFi-Sensing-Classification
                startedAt: "2026-05-11T15:12:44.169991Z"
                writerId: 069cc3y7shz1lpashpt5fjqcs8mruyus
        m: []
        python_version: 3.13.13
        t:
            "1":
                - 1
                - 5
                - 6
                - 53
            "2":
                - 1
                - 5
                - 6
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.13
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
C:
    value: 15
cv_folds:
    value: 5
gamma:
    value: 0.0125
kernel:
    value: rbf
model_name:
    value: SVC
scoring_metric:
    value: f1_macro
