# Data settings
data_path: "data/processed/train_boxcox.csv"
test_data_path: "data/processed/test_boxcox.csv"
target_col: "position"
test_size: 0.2
models_dir: "outputs/models"
experiments_dir: "outputs/experiments"
submissions_dir: "outputs/submissions"

# Training settings
model_name: "knn"
cv_folds: 5
scoring: "f1_macro"

# Hyperparameter Search Space
param_grid:
  n_neighbors: [3, 5, 9, 15]
  weights: ['uniform', 'distance']
  p: [1, 2] # 1 = Manhattan distance, 2 = Euclidean distance