# Data settings
train_path: "data/processed/X_train_non_scaled.csv"
val_path: "data/processed/X_val_non_scaled.csv"
test_path: "data/processed/X_test_non_scaled.csv"
y_train_path: "data/processed/y_train.csv"
y_val_path: "data/processed/y_val.csv"

target_col: "position"
test_size:  0.2

# Training settings
model_name: "rfe"
cv_folds: 3
scoring: "f1_macro"

param_grid:
  # --- FROZEN STAGE 1 WINNERS (Making the internal RF fast) ---
  - estimator__n_estimators: [200]
    estimator__max_depth: [20]
  
  # --- THE PARAMETERS WE ACTUALLY TUNE ---
    n_features_to_select: [50, 100, 120]
    step: [0.2, 0.5, 1]