# Data settings
data_path: "data/raw/train_nt.csv" # Adjust based on your chosen dataset
test_data_path: "data/raw/test_nolabels_nt.csv"
target_col: "position"
test_size: 0.2

# Training settings
model_name: "svm"
cv_folds: 5
scoring: "f1_macro"

# Hyperparameter Search Space
param_grid:
  kernel: ['rbf']
  C: [0.1, 1, 10, 15, 100]
  gamma: ['scale', 'auto', 0.0125, 0.1]