# --- DATA SETTINGS ---
data_path: "data/raw/train_nt.csv"
test_data_path: "data/raw/test_nolabels_nt.csv"
target_col: "position"
test_size: 0.2


# --- TRAINING SETTINGS ---
model_name: "gmm"
cv_folds: 3
scoring: "f1_macro"

# --- HYPERPARAMETERS ---
param_grid:
  # GMMs look at the shape/variance of the data, not just the physical distance.
  n_clusters: [10, 15, 20, 30]