data_path: "data/raw/train_nt.csv"
test_data_path: "data/raw/test_nolabels_nt.csv"
target_col: "position"

model_name: "lda"
cv_folds: 5
scoring: "f1_macro"


param_grid:
  solver: ["lsqr", "eigen"]
  shrinkage: [0.0, 0.5, 1.0]