# Data settings
data_path: "data/raw/train_nt.csv" # Adjust based on your chosen dataset
test_data_path: "data/raw/test_nolabels_nt.csv" # Ensure this matches the train data type
target_col: "position"
test_size: 0.2
models_dir: "outputs/models"
experiments_dir: "outputs/experiments"
submissions_dir: "outputs/submissions"

# Training settings
model_name: "mlp"
cv_folds: 3
scoring: "f1_macro"

# Hyperparameter Search Space
param_grid:
  hidden_layer_sizes: 
    - [50]
    - [100]
    - [50, 50]
  activation: ['relu', 'tanh']
  alpha: [0.0001, 0.001, 0.01]
  max_iter: [500]