# Data settings
data_path: "data/processed/train_lof_boxcox.csv" # Adjust based on your chosen dataset
test_data_path: "data/processed/test_lof_boxcox.csv" # Ensure this matches the train data type
target_col: "position"
test_size: 0.2

# Training settings
model_name: "svm"
cv_folds: 5
scoring: "f1_macro"

is_clean_data: false
outlier_method: lof 

# Hyperparameter Search Space
param_grid:
  kernel: ['rbf']
  C: [15]          # Setting the optimal C directly
  gamma: [0.0125]  # Setting the optimal gamma directly