# Data settings
data_path: "data/processed/train_iqr.csv"
test_data_path: "data/processed/test_original.csv" # NEVER use test_iqr!
target_col: "position"
test_size: 0.2
models_dir: "outputs/models"
experiments_dir: "outputs/experiments"
submissions_dir: "outputs/submissions"

# Training settings
model_name: "logistic"
cv_folds: 5
scoring: "f1_macro"

# Hyperparameter Search Space
param_grid:
  solver: ['lbfgs', 'saga']
  C: [0.01, 0.1, 1.0, 10.0]     # Inverse of regularization strength
  max_iter: [1000]              # Needs more iterations to converge