# NOTA: COMO USAR
# 1- Entrenar un svm. En la param_grid, ponemos los mejores hiperparámetros encontrados
# 2- Entrenar un random forest. En la param_grid, ponemos los mejores hiperparámetros encontrados
# 3- Entrenar un xgboost. En la param_grid, ponemos los mejores hiperparámetros encontrados

# Asi no tarda la vida
# 4- Entrenar el voting. En la param_grid, solo ponemos los hiperparámetros del meta-modelo (final_estimator), porque los otros ya los hemos fijado en los pasos anteriores (ara cv con ese)


# Data settings
data_path: "data/processed/train_features.csv"
test_data_path: "data/processed/test_features.csv"
target_col: "position"

# Training settings
model_name: "voting"
cv_folds: 5
scoring: "f1_macro"

param_grid:
  # --- FROZEN STAGE 1 WINNERS ---
  svm__C: [15]
  svm__gamma: [0.0125]
  svm__kernel: ['rbf']

  rf__n_estimators: [300]
  rf__max_depth: [30]

  xgb__n_estimators: [500]
  xgb__learning_rate: [0.1]
  xgb__max_depth: [5]
  xgb__colsample_bytree: [0.8]
  xgb__gamma: [0]
  xgb__subsample: [0.8]
  
  # --- THE PARAMETERS WE ACTUALLY TUNE ---
  weights: 
    - [1, 1, 1]  
    - [2, 1, 1]  
    - [1, 2, 1]  
    - [1, 1, 2]