train_path: "data/processed/X_train_standard_scaled.csv"
val_path: "data/processed/X_val_standard_scaled.csv"
test_path: "data/processed/X_test_standard_scaled.csv"
y_train_path: "data/processed/y_train.csv"
y_val_path: "data/processed/y_val.csv"

target_col: "position"
test_size:  0.2

model_name: "svm"
cv_folds:   5
scoring:    "f1_macro"

param_grid:
    kernel: ['rbf']
    C:      [10, 15]
    gamma:  [0.0125, 'scale']