_wandb:
    value:
        cli_version: 0.26.1
        e:
            9y82r53c4j5ow254q5438q5f97cksva9:
                args:
                    - train
                    - .\config\gmm.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 10
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1021821579264"
                        used: "251150786560"
                email: laura.rebollo.crespo@estudiantat.upc.edu
                executable: C:\Users\laura\Desktop\UNI\Q4\AA1\ML-WiFi-Sensing-Classification\.venv\Scripts\python.exe
                git:
                    commit: db0804a7cbdb044335d63b7d58678ecdb33b1dca
                    remote: https://github.com/laurarebollocrespo/ML-WiFi-Sensing-Classification.git
                host: DESKTOP-M6J13KT
                memory:
                    total: "33818390528"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\laura\Desktop\UNI\Q4\AA1\ML-WiFi-Sensing-Classification\main.py
                python: CPython 3.13.13
                root: C:\Users\laura\Desktop\UNI\Q4\AA1\ML-WiFi-Sensing-Classification
                startedAt: "2026-05-11T14:17:21.196672Z"
                writerId: 9y82r53c4j5ow254q5438q5f97cksva9
        m: []
        python_version: 3.13.13
        t:
            "1":
                - 1
                - 5
                - 6
                - 53
            "2":
                - 1
                - 5
                - 6
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.13
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
cv_folds:
    value: 3
model_name:
    value: SupervisedClusteringWrapper
n_clusters:
    value: 15
scoring_metric:
    value: f1_macro
